# This workflow will build a MuleSoft project and deploy to CloudHub
name: Build and Deploy Mule Application

on:
  pull_request:
    types: [ closed ]
    branches: [ main, qa, dev ]
  workflow_dispatch:
    
jobs:
  prepare:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
        environment: ${{ steps.set_vars.outputs.environment }}
        appNameSuffix: ${{ steps.set_vars.outputs.appNameSuffix }}
    steps:
    - name: Extract branch name
      id: extract_branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      
    - name: Print branch name
      run: echo "Branch ${{ steps.extract_branch.outputs.branch }}"
    
    - name: Set variables
      id: set_vars
      run: |
        echo "##[set-output name=environment;]$(echo "${{ steps.extract_branch.outputs.branch }}" | tr '[:lower:]' '[:upper:]')"
        if [[ "${{ steps.extract_branch.outputs.branch }}" != "main" ]]; then
          echo "##[set-output name=appNameSuffix;]$(echo "-${{ steps.extract_branch.outputs.branch }}" | tr '[:upper:]' '[:lower:]')"
        fi
    
    - name: Print variables
      run: |
        echo "Env ${{ steps.set_vars.outputs.environment }}"
        echo "Suffix ${{ steps.set_vars.outputs.appNameSuffix }}"
      
  build:
    runs-on: ubuntu-latest
    needs: prepare
    environment:
        name: ${{ needs.prepare.outputs.environment }}
    outputs: 
      client_id: ${{ secrets.CLIENT_ID }}
    steps:
    - name: Print Env Secret
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
      run: |
        echo "KEY: $CLIENT_ID"
        echo ${{ secrets.CLIENT_ID }}
        echo "::set-output name=client_id::${{ secrets.CLIENT_ID }}"
        
  deploy:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    environment:
        name: ${{ needs.prepare.outputs.environment }}
        
    steps: 
    - name: Print vars
      run: |
        echo "KEY: $CLIENT_ID"
        echo ${{ secrets.CLIENT_ID }}
        echo ${{ needs.build.outputs.client_id }}
  
