# This workflow will build a MuleSoft project and deploy to CloudHub
name: Build and Deploy Mule Application

on:
  pull_request:
    types: [ closed ]
    branches: [ main, qa, dev ]
  workflow_dispatch:
    
jobs:
  prepare:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
        environment: ${{ steps.set_vars.outputs.environment }}
        appNameSuffix: ${{ steps.set_vars.outputs.appNameSuffix }}
        secretSuffix: ${{ steps.step_vars.outputs.secretSuffix }}
        secretName: ${{ steps.step_vars.outputs.secretName }}
    steps:
    - name: Extract branch name
      id: extract_branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      
    - name: Print branch name
      run: echo "Branch ${{ steps.extract_branch.outputs.branch }}"
    
    - name: Set variables
      id: set_vars
      run: |
        echo "##[set-output name=environment;]$(echo "${{ steps.extract_branch.outputs.branch }}" | tr '[:lower:]' '[:upper:]')"
        if [[ "${{ steps.extract_branch.outputs.branch }}" != "main" ]]; then
          echo "##[set-output name=appNameSuffix;]$(echo "-${{ steps.extract_branch.outputs.branch }}" | tr '[:upper:]' '[:lower:]')"
        fi
        echo "##[set-output name=secretSuffix;]$(echo "-${{ steps.extract_branch.outputs.branch }}" | tr '[:lower:]' '[:upper:]')"
        echo "##[set-output name=secretName;]$(echo "CLIENT_ID_${{ steps.extract_branch.outputs.branch }}" | tr '[:lower:]' '[:upper:]')"
        
    - name: Print variables
      run: |
        echo "Env ${{ steps.set_vars.outputs.environment }}"
        echo "Suffix ${{ steps.set_vars.outputs.appNameSuffix }}"
        echo "secret suffix ${{ steps.set_vars.outputs.secretSuffix }}"
        echo "secret name ${{ steps.set_vars.outputs.secretName }}"
      
  build:
    runs-on: ubuntu-latest
    needs: prepare
    environment:
        name: ${{ needs.prepare.outputs.environment }}
    outputs: 
      client_id: ${{ steps.set_vars.outputs.client_id }}
    env:
      SECRET_NAME: ${{ needs.prepare.outputs.secretName }}
    steps:
    - name: Print Env Secret
      id: set_vars
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        SECRET_ID: ${{ secrets[env.SECRET_NAME] }}
        CLIENT_ID_DEV: ${{ secrets[format('CLIENT_ID_{0}', needs.prepare.outputs.secretSuffix)] }}
      run: |
        echo KEY: $CLIENT_ID
        echo ${{ secrets.CLIENT_ID }}
        echo SECRET_ID - ${{ secrets[env.SECRET_NAME] }}
        echo CLIENT_ID_DEV: $CLIENT_ID_DEV
        echo SECRET_NAME: $SECRET_NAME
        echo SECRET_ID: $SECRET_ID
        printenv | grep CLIENT_ID_
        printenv | grep SECRET_
        
  deploy:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    environment:
        name: ${{ needs.prepare.outputs.environment }}
    steps: 
    - name: Print vars
      run: |
        echo ${{ secrets.CLIENT_ID }}
        echo ${{ needs.build.outputs.client_id }}
  
